"""Add confirmed column to user table

Revision ID: 81794caf51d9
Revises: 
Create Date: 2024-12-28 00:31:33.894453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81794caf51d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
